# Generated by Django 4.2 on 2023-04-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0002_remove_task_is_completed_task_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Board',
        ),
    ]
