# Generated by Django 4.2 on 2023-04-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0003_rename_table_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager_app.board'),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
