# Generated by Django 4.2 on 2023-04-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0004_alter_task_column_delete_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='column',
            new_name='board',
        ),
    ]
